### ISSUE TITLE
Doku: $REX['SERVER'] u.a. korrigieren

### ISSUE THREAD

**Issue by alexplusde** [tyrant88/search_it#12]
Die meisten Ausgabe-Module müssten intakt sein, wenn $REX durch das Äquivalent in R5 ersetzt wird.

Beim Such-Eingabefeld-Beispiel wäre `method="post"` empfehlenswert, sonst wird die URL so komisch und bei `action=""` sollte eine redaxo-URL rein mit dem Hinweis, dass die ID der ID des Suchergebnisses entsprechen muss. Außerdem überall vorbildlich rex_request() verwenden statt $_REQUEST oder $_GET

**Comment by tyrant88** [comment]
Das erste Beispiel Modul in der Doku habe ich mal auf R5 portiert.

**Comment by alexplusde** [comment]
In der Demo, die ich dir zur Verfügung gestellt habe, korrigiere ich gerade alle Beispiele.
