### ISSUE TITLE
Feature: Where-Klauseln für Datenbanktabellen

### ISSUE THREAD

**Issue by alexplusde** [tyrant88/search_it#13]
Bisher können Datenbank-Felder nicht eingeschränkt werden, sodass bei Datenbank-Suchen auch Einträge gefunden werden, die auf `active=0`,`disabled=1`,`online=0` etc. stehen. 

Diese können im Moment erst ausgefiltert werden, wenn die Suchergebnisse schon ausgegeben werden und auch nur dann, wenn das entsprechende Feld active/disabled/online indiziert wurde.

**Comment by tyrant88** [comment]
Das Feature verstehe ich, ein Filter wäre von Nöten, das müsste wahrscheinlich unter den Spalten pro Tabelle sitzen... eine WHERE Bedingung für jede Tabelle. Als Freitext? "disabled != 0 AND unwanted = 12"

**Comment by alexplusde** [comment]
Mal ne blöde Frage: Lässt sich so ein Feature für Datenbank-Tabellen nicht auf Basis einer `VIEW` in MySQL umsetzen?

1. `VIEW` aus Datenbanktabelle erstellen (mit `WHERE`-Einschränkungen)
2. `search_it` diese View durchsuchen lassen
3. freuen ;)

**Comment by alexplusde** [comment]
Also eine erstellte `VIEW` taucht auf jeden Fall auch in `Search it` auf.

Memo: Bei manchen Hostern wird das Erstellen einer `VIEW` unterbunden. Alternativ könnte man eine ganz normale Tabelle erstellen, die regelmäßig eine `SELECT ... WHERE ...`-Abfrage in eine neue Tabelle schreibt.

Danke @nilsology für die Unterhaltung gestern, du hast mich ja unbewusst auf diese Idee gebracht :)

**Comment by alexplusde** [comment]
@tyrant88 PR ist bereit zum mergen. Schau bitte bei Gelegenheit drauf, obs passt :)

**Comment by alexplusde** [comment]
Ich deute das als: "Passt."

**Comment by tyrant88** [comment]
Ich dachte du hättest eine Nachricht bekommen, als ich gemerged habe...

**Comment by tyrant88** [comment]
Und ich bin immer noch am überlegen, ob man nicht doch ein Feld für WHERE Klauseln unter die Tabellen/Spalten-Auswahl setzt...
