### ISSUE TITLE
Doku: Objekt-Methoden vorstellen

### ISSUE THREAD

**Issue by alexplusde** [tyrant88/search_it#14]
Was bisher nirgends wirklich erklärt wird, sind die einzelnen Methoden, die das search_it-Objekt zur Verfügung stellt:

ab https://github.com/tyrant88/search_it/blob/master/lib/search_it.php#L251

`setSearchInIDs()`, `setMaxTeaserChars`, etc.

**Comment by alexplusde** [comment]
Ist nun in der Doku unter search_it-reference.md begonnen, wird aber von mir mangels Wissen nicht fortgeführt. Freiwillige vor :)

Mit freundlicher Unterstützung von unserem Azubi @pixelfirma.

**Comment by tyrant88** [comment]
Fertig.
