### ISSUE TITLE
Doku: Howto: Reindexieren via Cronjob

### ISSUE THREAD

**Issue by alexplusde** [tyrant88/search_it#15]
Beispiele für
- Für Datenbank-Felder
- Artikel und Kategorien
- Medienpool-Dateien

**Comment by alexplusde** [comment]
Memo:
- Allgemein: Wann findet ein Reindex statt, wie kann man ihn manuell anstoßen? 
- Im Forum wurde berichtet, dass Datenbankänderungen nicht übernommen wurden -> Testen
- Im Forum wurde berichtet, dass bearbeitete Blöcke, die in einem Offline-Artikel sind, beim Online-Schalten nicht berücksichtigt wurden -> Testen

**Comment by alexplusde** [comment]
Wenn Einstellungen an der Suchergebnis-Darstellung vorgenommen werden, muss der Such-Cache gelöscht werden. Sonst bleibt es bei der alten Darstellung (bspw. Anzahl der Treffer/Zeichen/Teaser)

**Comment by dergel** [comment]
mittlerweile kann das cronjobaddon ja auch echte Zeiten. D.h. man kann steuern, ob man nachts einen neuen index erstellt. D.h. dann weiss man, dass mindestens alles tagesaltuell ist

**Comment by alexplusde** [comment]
@dergel wie kommst du denn hier her ;)

**Comment by tyrant88** [comment]
Ich hab @phoebusryan ein issue für den emailobfuscator gedrückt. Da hat er wohl nachgekuckt "wer isn das, was macht der denn so, dass der sich traut mir ein issus zu schreiben" und hat es dann im slack gepetzt. :-) Jetzt wissen alle Bescheid.

**Comment by alexplusde** [comment]
Memo: Wie eine Datenbank-Spalte neu indiziert wird:

```
<?php

$xsearch = new RexSearch;

$xsearch->indexColumn('rex_article', 'seo_description', 'id');
$xsearch->indexColumn('rex_article', 'seo_keywords', 'id');
$xsearch->indexColumn('rex_xf_charts', 'title', 'id');
$xsearch->indexColumn('rex_xf_charts', 'interpret', 'id');

?>
```

@tyrant88 wie funktioniert das mit der Reindexierung von Artikeln? Dann könnte man den passenden Cronjob schon mal  in die Doku zur `howto-reindex.md` packen.

**Comment by tyrant88** [comment]
Die Spalten würde man so machen:

 
foreach($search_it->includeColumns as $table => $columnArray){
        foreach($columnArray as $column) {
            $search_it->indexColumn($table, $column);
        }
}

 
Dann werden alle Spalten mit “Häkchen” neu indiziert.

 
 
Artikel:


$art_sql = rex_sql::factory();
$art_sql->setTable($search_it->tablePrefix.'article');
if($art_sql->select('id,clang_id')){
    foreach($art_sql->getArray() as $art){
        $search_it->indexArticle($art['id'], $art['clang_id']);
    }
}

 
 
 
 
Von: Alexander Walther [mailto:notifications@github.com] 
Gesendet: Montag, 26. September 2016 20:24
An: tyrant88/search_it
Cc: Norbert Micheel; Mention
Betreff: Re: [tyrant88/search_it] Doku: Howto: Reindexieren via Cronjob (#15)

 
Memo: Wie eine Datenbank-Spalte neu indiziert wird:


<?php


 

$xsearch = new RexSearch;


 

$xsearch->indexColumn('rex_article', 'seo_description', 'id');


$xsearch->indexColumn('rex_article', 'seo_keywords', 'id');


$xsearch->indexColumn('rex_xf_charts', 'title', 'id');


$xsearch->indexColumn('rex_xf_charts', 'interpret', 'id');


 

?>

@tyrant88 wie funktioniert das mit der Reindexierung von Artikeln? Dann könnte man den passenden Cronjob schon mal in die Doku zur howto-reindex.md packen.

**Comment by alexplusde** [comment]
Na, perfekt! Damit lässt sich doch arbeiten.

**Comment by alexplusde** [comment]
Fürs Protokoll: Ich hab den Code mal in die Demo als Cronjob kopiert, aber es kracht. Evtl. Syntax-Fehler, evtl. auch was anderes.

**Comment by tyrant88** [comment]
Jetzt gibt es einen cronjob-Typ "Re-indizieren" bei dem man auswählen kann: kompletter Index, nur Tabellen oder nur Article.
Will damit nur erstmal die Möglichkeit schaffen.
Was dann wirklich sinnvoll ist, sollten wir dann alle diskutieren.

**Comment by alexplusde** [comment]
`*bravo*` Rex-Taler gibt's in Slack.

**Comment by tyrant88** [comment]
wieso war das noch offen?

**Comment by alexplusde** [comment]
Der Text in der Doku ist noch nicht aktualisiert.

**Comment by alexplusde** [comment]
Wenn gemerged, bitte schließen

**Comment by tyrant88** [comment]
merged
