### ISSUE TITLE
Einstellungen Suchergebnis: Whitelist, Blacklist als textarea

### ISSUE THREAD

**Issue by alexplusde** [tyrant88/search_it#17]
Es gibt in https://github.com/tyrant88/search_it/blob/master/lib/search_it.php#L1334 eine Möglichkeit, Begriffen eine Gewichtung mitzugeben, allerdings findet man dafür keine Einstellung.

Blacklist-Begriffe sollten als Textarea formatiert werden, damit sie einfacher zu lesen sind.

**Comment by tyrant88** [comment]
Textarea ist drin

**Comment by alexplusde** [comment]
Komisch, ich hab mir gerade den aktuellen Stand gezogen - keine Änderung. 

![image](https://cloud.githubusercontent.com/assets/3855487/18471061/3a223aca-79b0-11e6-9ab2-d720b66ed7b1.png)

**Comment by tyrant88** [comment]
Sorry, hatte das letzte „push“ vergessen…

 
 
Von: Alexander Walther [mailto:notifications@github.com] 
Gesendet: Dienstag, 13. September 2016 12:48
An: tyrant88/search_it
Cc: Norbert Micheel; State change
Betreff: Re: [tyrant88/search_it] Einstellungen Suchergebnis: Whitelist, Blacklist als textarea (#17)

 
Komisch, ich hab mir gerade den aktuellen Stand gezogen - keine Änderung.
