### ISSUE TITLE
Darstellungsfehler Dateisuche

### ISSUE THREAD

**Issue by alexplusde** [tyrant88/search_it#2]
Die multiselect-Eingabefelder sollten immer volle Breite bekommen - sicherlich fehlt bloß eine Bootstrap-Klasse o.ä.

![image](https://cloud.githubusercontent.com/assets/3855487/18199709/d8beecf8-7101-11e6-9786-bd04e4cc6fa1.png)

**Comment by tyrant88** [comment]
erledigt
