### ISSUE TITLE
Beispiele: Standard-Such-Parameter von ?search_it= auf ?q= oder ?s= ändern.

### ISSUE THREAD

**Issue by alexplusde** [tyrant88/search_it#20]
Diese Parameter werden von Tracking-Anwendungen automatisch erkannt.

Siehe 
* http://piwik.org/docs/site-search/#track-site-search-using-url-parameters-default
* https://support.google.com/analytics/answer/1012264?hl=de

**Comment by tyrant88** [comment]
Das betrifft nur die Module, oder? Da gibt search it doch sonst nichts vor?

**Comment by alexplusde** [comment]
Stimmt eigentlich.

**Comment by alexplusde** [comment]
Kannst du mich evtl. in das Repository aufnehmen, damit ich mir selbst Issues wie dieses zuweisen kann und sie für mich als Erinnerung offen lasse?

**Comment by alexplusde** [comment]
Die Beispiele wurden entsprechend angepasst.
