### ISSUE TITLE
Settings im Data-Ordner ablegen

### ISSUE THREAD

**Issue by alexplusde** [tyrant88/search_it#24]
Soweit ich das überblicken kann, werden die Settings nicht im Data-Ordner abgelegt.

**Comment by tyrant88** [comment]
Warum sollten sie?

Jetzt gibt es ja die Config Values in rex_config

 
 
 
Von: Alexander Walther [mailto:notifications@github.com] 
Gesendet: Dienstag, 13. September 2016 12:59
An: tyrant88/search_it
Betreff: [tyrant88/search_it] Settings im Data-Ordner ablegen (#24)

 
Soweit ich das überblicken kann, werden die Settings nicht im Data-Ordner abgelegt.

**Comment by alexplusde** [comment]
Bleiben die Einstellungen dann updatefähig? Ich hatte jetzt search_it deinstalliert, dann die aktuelle GitHub-Version installiert und es sah für mich so aus, als ob dann alle Einstellungen zurückgesetzt wurden.

**Comment by tyrant88** [comment]
Da gab es ja gerade Slack von gregor ne Ansage. De-Installieren ist völlig plattmachen, Re-installieren erschafft ne "saubere" Installation. 
Alle anderen Addons (die ich habe) speichern auch keine Einstellungen im Data-Ordner, nur eigene - ich nenne es mal "Erzeugnisse"

**Comment by alexplusde** [comment]
okay. Wenn das so passt, passt es :) 

Ich war nur verwundert, hänge da aber glaube ich auch zu sehr in der Struktur von R4.
