### ISSUE TITLE
Doku: Korrekturen Beispielmodule

### ISSUE THREAD

**Issue by alexplusde** [tyrant88/search_it#25]
Bei dem Beispiel mit der komplexen Suche kommt es zu einem Fehler, wenn man "Unterkategorien durchscuhen" aktiviert:
```
"ErrorException" thrown in rex:///module/16/output on line 52
Fatal error: Call to undefined function a587_getCategories()
```

Ändern in: search_it_getCategories()

**Comment by tyrant88** [comment]
Die Beispiele sind alle nicht überarbeitet… außer dem ersten.

 
 
Von: Alexander Walther [mailto:notifications@github.com] 
Gesendet: Dienstag, 13. September 2016 13:00
An: tyrant88/search_it
Betreff: [tyrant88/search_it] Komplexe Suche: a587_getCategories() nicht vorhanden (#25)

 
Bei dem Beispiel mit der komplexen Suche kommt es zu einem Fehler, wenn man "Unterkategorien durchscuhen" aktiviert:


"ErrorException" thrown in rex:///module/16/output on line 52


Fatal error: Call to undefined function a587_getCategories()

**Comment by alexplusde** [comment]
Ok, dann behalte ich das mal auf dem Schirm und schaue, wie ich das anpassen muss. Bitte offen lassen.

**Comment by alexplusde** [comment]
`        $search_it->setLimit(array($start = isset(rex_get('start', 'int', 0))? intval(rex_get('start', 'int', 0)):0, SHOWMAX));`

...wirft Fehler. Das isset ist unnötig, oder? Stattdessen müsste rex_request ja mit Default-Value reichen:

`        $search_it->setLimit(array($start = rex_request('start', 'int', 0), SHOWMAX));`

**Comment by alexplusde** [comment]
Memo: Reine Datenbank-Suchergebnisse als Beispiel-Modul.

**Comment by alexplusde** [comment]
Um Fehler zu vermeiden, sollte der letzte Abfrage-Typ von einem is_object() eingeschlossen werden. Falls dieser auch nicht den $hit richtig verarbeitet, weil es bspw. kein Artikel oder kein Medium ist, sollte eine Warnmeldung ausgegeben werden. Dann wurde schlichtweg ein Suchtreffer-Typ (bspw. Datenbanksuche) nicht abgefragt.

```
                // Artikel oder DB-Spalte aus der Artikel-Tabelle
                $article = rex_article::get($hit['fid']);
                print_r($hit);
                if(is_object($article)) {
                    echo '    <li>
          <h4><a href="'.htmlspecialchars($article->getUrl()).'">'.$article->getName().'</a></h4>
          <p class="highlightedtext">'.$text.'</p>
          <p class="url">'.rex::getServer().rex_getUrl($hit['fid'], $hit['clang']).'</p>
        </li>';
                } else {
                     echo 'Ein Suchergebnis-Typ wurde nicht abgefangen';   
                }
```

Demo-Modul 15 und 16 sind bereits entsprechend korrigiert.

**Comment by alexplusde** [comment]
Beispiele wurden alle angepasst (Demo-Installation) und müssen noch in die Doku übernommen werden. Aber das Issue ist für mich erst mal erledigt.
