### ISSUE TITLE
Automatische Indexierung nach ADD/EDIT/DELETE

### ISSUE THREAD

**Issue by alexplusde** [tyrant88/search_it#26]
Scheint nicht zu funktionieren. Habe gerade einen Text-Block in einen Artikel eingefügt und "Begriff" eingegeben, aber "Begriff" taucht in der Datenbank in _keywords erst nach einer neuen Indexierung auf.

**Comment by tyrant88** [comment]
Du hattest was von Einstellungen und re-installieren gesagt, deshalb meine Frage:

Ist die Option „Artikel (ADD, EDIT, DELETE) automatisch (de)indexieren“ noch aktiviert?

 
 
Von: Alexander Walther [mailto:notifications@github.com] 
Gesendet: Dienstag, 13. September 2016 14:46
An: tyrant88/search_it
Betreff: [tyrant88/search_it] Automatische Indexierung nach ADD/EDIT/DELETE (#26)

 
Scheint nicht zu funktionieren. Habe gerade einen Text-Block in einen Artikel eingefügt und "Begriff" eingegeben, aber "Begriff" taucht in der Datenbank in _keywords erst nach einer neuen Indexierung auf.

**Comment by alexplusde** [comment]
Ja. Anderes Projekt, 
- frische Installation
- Abspeichern aller Settings
- Indexierung
- Block mit Text hinzugefügt
- Suche -> kein Ergebnis
- Reindexerung
- Suche -> Ergebnis

**Comment by alexplusde** [comment]
evtl. liegt es daran, dass der Suchcache nicht erneuert wird, wenn der Begriff schon mal gesucht wurde. Ich teste noch.

**Comment by alexplusde** [comment]
Manchmal muss man nur den Suchcache löschen, manchmal komplett neu indexieren. Es scheint auf jeden Fall so, dass ADD/EDIT/DELETE nicht für die Suche berücksichtigt wird, trotz entsprechender Einstellungen.

Können wir ja vlt. morgen nochmal gemeinsam anschauen.

**Comment by alexplusde** [comment]
betrifft evtl.:

http://www.redaxo.org/de/forum/addons-f30/addon-rexsearch-fulltext-search-addon-t12965-630.html#p113322

```
[...]
2. Beim Erstellen eines Artikels und darin eines Slices wurde der Index nicht neu erstellt. Sehr unschön :(
Durch das Hinzufügen folgender Zeilen klappt dies nun auch:
function.in.php:a587_handle_extensionpoint (Ab Zeile 211 irgendwo als case):
CODE: ALLES AUSWÄHLEN
case 'ART_CONTENT_UPDATED':
    $rexsearch->indexArticle($_params['id'],$_params['clang']);
break;

Und den Extension-Point zum Array hinzufügen in config.inc.php:
CODE: ALLES AUSWÄHLEN
$extensionPoints = array(
[...] 
    'SLICE_UPDATED',
    'ART_CONTENT_UPDATED'
);
  
a587_register_extensionpoints($extensionPoints);


Mit diesen Änderungen läuft das AddOn nun zumindest bei mir.

Wäre super, wenn diese Änderungen auch in die neueste Version übernommen werden könnten.

Gruß

Björn
```

**Comment by alexplusde** [comment]
Ich habe gerade noch etwas in anderen Repos gestöbert:

https://github.com/tyrant88/search_it/blob/master/boot.php#L41-L53

gehören da noch weitere EPs hin?
https://github.com/chip75/rexsearch/commit/367e13eed7b0b414d6970b5a4a3951adb6c77683

Oder werden die auch durch ART_UPDATED abgefangen?

**Comment by tyrant88** [comment]
Ich hab sie eingebaut.

 
Von: Alexander Walther [mailto:notifications@github.com] 
Gesendet: Montag, 26. September 2016 20:43
An: tyrant88/search_it
Cc: Norbert Micheel; Comment
Betreff: Re: [tyrant88/search_it] Automatische Indexierung nach ADD/EDIT/DELETE (#26)

 
Ich habe gerade noch etwas in anderen Repos gestöbert:

https://github.com/tyrant88/search_it/blob/master/boot.php#L41-L53

gehören da noch weitere EPs hin?
chip75/rexsearch@367e13e

Oder werden die auch durch ART_UPDATED abgefangen?

**Comment by alexplusde** [comment]
Tests:
Einstellung Offline-Artikel indexieren ist ausgeschaltet:
* Artikel anlegen
* Artikel online schalten: Alle Begriffe in Slices werden indexiert
* Artikel offline schalten: Alle Begriffe in Slices werden deindexiert
* Slice anlegen: Alle Begriffe im Slice werden indexiert
* Slice löschen: **Begriffe bleiben im Index**
* Artikel löschen: Alle Begriffe in Slices werden deindexiert

**Comment by tyrant88** [comment]
Den Fehler hatte ich schon gefunden, wird im nächsten push erledigt.

 
Von: Alexander Walther [mailto:notifications@github.com] 
Gesendet: Dienstag, 27. September 2016 18:25
An: tyrant88/search_it
Cc: Norbert Micheel; Assign
Betreff: Re: [tyrant88/search_it] Automatische Indexierung nach ADD/EDIT/DELETE (#26)

 
Tests:
Einstellung Offline-Artikel indexieren ist ausgeschaltet:

*	Artikel anlegen
*	Artikel online schalten: Alle Begriffe in Slices werden indexiert
*	Artikel offline schalten: Alle Begriffe in Slices werden deindexiert
*	Slice anlegen: Alle Begriffe im Slice werden indexiert
*	Slice löschen: Begriffe bleiben im Index 
*	Artikel löschen: Alle Begriffe in Slices werden deindexiert

**Comment by tyrant88** [comment]
gefixt. bitte testen.

**Comment by alexplusde** [comment]
Scheint zu funktionieren.

https://github.com/tyrant88/search_it/commit/87b76b2944e6ac9776113194e39b8b9dc60f2b60
