### ISSUE TITLE
Enhancement: Nach speichern der Settings Indexierung vorschlagen

### ISSUE THREAD

**Issue by alexplusde** [tyrant88/search_it#27]
Meines Wissens ist es mindestens bei der Seite `Quelle` erforderlich, dass der Suchindex erneuert wird. Dazu sollte bei der Meldung `Einstellungen wurden gespeichert.` mind. ein Button `Suchindex jetzt erneuern.` angeboten werden.

**Comment by tyrant88** [comment]
Eh? Eigentlich sollte beim Speichern von gewissen Parametern die Meldung eingeblendet werden „Der Suchindex sollte erneuert werden“… Muss ich mal prüfen, warum das nicht mehr geht.

 
 
Von: Alexander Walther [mailto:notifications@github.com] 
Gesendet: Mittwoch, 14. September 2016 10:52
An: tyrant88/search_it
Betreff: [tyrant88/search_it] Enhancement: Nach speichern der Settings Indexierung vorschlagen (#27)

 
Meines Wissens ist es mindestens bei der Seite Quelle erforderlich, dass der Suchindex erneuert wird. Dazu sollte bei der Meldung Einstellungen wurden gespeichert. mind. ein Button Suchindex jetzt erneuern. angeboten werden.

**Comment by tyrant88** [comment]
fixed.

**Comment by alexplusde** [comment]
Die Meldung kommt, aber noch besser wäre es, wenn gleich "vollständige Indexierung" und "Schrittweise Indexierung" als Button in der Meldung sind.
