### ISSUE TITLE
Statistik: Keyword zusammenfassen, wenn es Treffer und keine Treffer gab.

### ISSUE THREAD

**Issue by alexplusde** [tyrant88/search_it#28]
In der R4-Version war es so:

Wenn ein Suchbegriff nicht gefunden wurde, dann wird ja seitens der Statistik mitgezählt, wie oft er nicht gefunden wurde. Sobald es den Suchbegriff gibt, wird für die Statistik das Keyword erneut angelegt und ausgegeben, wie viele Suchen davon erfolgreich waren. (Siehe Bild: `Vertretungsplan`)

Auch Groß-/Kleinschreibung, die bei der Suche meines Wissens ignoriert wird, wird in der Statistik getrennt ausgegeben. Durch diese Darstellung wird die Statistik in meinen Augen verfälscht. (Siehe: `bogy/BOGY/Bogy`)

![image](https://cloud.githubusercontent.com/assets/3855487/18506733/a1222416-7a6d-11e6-8cf2-2eed539765f7.png)

Würden die Werte addiert werden, wäre die Auswertung anders.

Vorschlag:

- Suchbegriffe zwar case sensitive in der Datenbank speichern, aber in der Statistik zusammenfassen, entweder häufigste Schreibweise ausgeben oder immer klein.
- Pro Begriff 3 Werte anzeigen: gesamt (grau), erfolglos (rot), erfolgreich (grün) (bei 0 erfolglosen oder 0 erfolgreichen Suchen bräuchte die Zahl 0 nicht ausgegeben werden)
- Evtl. als Tabelle formatieren und FooTable verwenden. http://fooplugins.github.io/FooTable/

**Comment by tyrant88** [comment]
Sorry, keine Ahnung wie du das hinbekommen hast ;;;;;-)
Die Liste wird mit einem MySQL "GROUP BY" gebildet das normalerweise Case insensitive ist.... Egal ob "test", "TESt", "tEST" bei mir wird das schön zusammen zusammen gefasst, obwohl alle einzeln in der searchterms_stats Tabelle stehen.

**Comment by alexplusde** [comment]
Dann werde ich das nochmal checken, vlt. war das nicht aus der aktuellsten r4-Version
Am 14.09.2016 6:00 nachm. schrieb tyrant88 <notifications@github.com>:Sorry, keine Ahnung wie du das hinbekommen hast ;;;;;-)
Die Liste wird mit einem MySQL "GROUP BY" gebildet das normalerweise Case insensitive ist.... Egal ob "test", "TESt", "tEST" bei mir wird das schön zusammen zusammen gefasst, obwohl alle einzeln in der searchterms_stats Tabelle stehen.

**Comment by alexplusde** [comment]
Ich mach's mal zu, bis mir der Fehler nochmal begegnet...
