### ISSUE TITLE
Search Higlighter: Einstellung speichern führt zum Frontend

### ISSUE THREAD

**Issue by alexplusde** [tyrant88/search_it#29]
Vermutlich fehlt /redaxo/ in der URL

**Comment by tyrant88** [comment]
Bei mir geht das. Auch mit frisch installierter Version. Es muss an einem konkreten Wert liegen, den du speichern willst...

**Comment by alexplusde** [comment]
![image](https://cloud.githubusercontent.com/assets/3855487/18544121/91ba1c92-7b33-11e6-8ad2-7db762fa76ef.png)

ist, was ich speichern möchte.

form gibt die index.php an, nicht die /redaxo/index.php

![image](https://cloud.githubusercontent.com/assets/3855487/18544153/abbc0510-7b33-11e6-9461-2da53550e659.png)

**Comment by tyrant88** [comment]
Also: index.php ist völlig korrekt, weil wir uns ja im Redaxo Verzeichnis befinden. "/index.php" wäre falsch-

Es lag an einem redirect (den ich glaube ich gar nicht brauche) der die Funktion rex::getServer()  nutzt. Da es bei mir funktionierte, nehme ich an du hattest bei dir keinen Slash am Ende der domain in der Backendeinstellung deiner Testumgebung.
Redirects hab ich raus genommen.

**Comment by alexplusde** [comment]
Da hast du natürlich recht. Den Slash am Ende der Domain gab's allerdings. Das Problem ist in jedem Fall aktuell gelöst.
