### ISSUE TITLE
Darstellungsfehler Statistik

### ISSUE THREAD

**Issue by alexplusde** [tyrant88/search_it#3]
![image](https://cloud.githubusercontent.com/assets/3855487/18199776/27784c72-7102-11e6-8ab3-f4e9c4088c44.png)

Am besten auf Zebralinien komplett verzichten, Fettdruck etc. nicht nötig. 

Die Auswertung könnte man (irgendwannTM) grafisch aufbohren.

**Comment by tyrant88** [comment]
much neater now

**Comment by alexplusde** [comment]
Wirklich hübsch!

Einzige Bemerkung: Hier schrift weiß machen:

![image](https://cloud.githubusercontent.com/assets/3855487/18471106/80087ca2-79b0-11e6-9659-1b8763b0255e.png)

**Comment by tyrant88** [comment]
Bei mir sieht es in Ordnung aus, ich nutze da nur die Bootstrap-Klassen….

 
 
 
Von: Alexander Walther [mailto:notifications@github.com] 
Gesendet: Dienstag, 13. September 2016 12:50
An: tyrant88/search_it
Cc: Norbert Micheel; State change
Betreff: Re: [tyrant88/search_it] Darstellungsfehler Statistik (#3)

 
Wirklich hübsch!

Einzige Bemerkung: Hier schrift weiß machen:

**Comment by alexplusde** [comment]
Google Chrome, Windows 10.
