### ISSUE TITLE
Datenbankfelder initial nicht auswählbar

### ISSUE THREAD

**Issue by alexplusde** [tyrant88/search_it#31]
![image](https://cloud.githubusercontent.com/assets/3855487/18623224/04209838-7e3b-11e6-96ac-30c8fbb7386d.png)

**Comment by tyrant88** [comment]
![zwischenablage-1](https://cloud.githubusercontent.com/assets/1277494/18626227/f6cb97b4-7e53-11e6-8c23-865d5a40d48b.jpg)

Nur vor dem ersten Speichern?

**Comment by alexplusde** [comment]
Tatsache.

**Comment by tyrant88** [comment]
Kann das dein Praktikant noch mal testen ? Im code kann ich es mir so nicht erklären. Sind dann wirklich keine checkboxen im Quellcode oder sind sie nur unsichtbar?

**Comment by alexplusde** [comment]
Scheint sich erledigt zu haben.
