### ISSUE TITLE
Search Highlighter: Black- / Whitelist an Tags, in denen ersetzt werden soll.

### ISSUE THREAD

**Issue by alexplusde** [tyrant88/search_it#32]
![image](https://cloud.githubusercontent.com/assets/3855487/18623609/a640d908-7e3f-11e6-8767-af0c61d89cc4.png)

Am besten wäre es, wenn man das Highlighting auf Elemente/Klassen beschränken könnte, um Ersetzungen in Meta-Daten, Menüs, etc. zu vermeiden.

**Comment by tyrant88** [comment]
So ich habe erstmal so umgesetzt, dass nur innerhalb des <body> ersetzt wird.

**Comment by alexplusde** [comment]
Klasse :)
