### ISSUE TITLE
Plaintext: Label korrigieren

### ISSUE THREAD

**Issue by alexplusde** [tyrant88/search_it#33]
![image](https://cloud.githubusercontent.com/assets/3855487/18623641/071891ee-7e40-11e6-9aa8-733a2fd4f7ee.png)

**Comment by tyrant88** [comment]
rex_i18n::rawMsg anstelle von $this-i18n "does the trick".
Ersteres macht eben kein htmlspecialchars(), dann bleibt der Link in der Sprachdatei ein Link
