### ISSUE TITLE
Plaintext: Werte in der Datenbank aufräumen

### ISSUE THREAD

**Issue by alexplusde** [tyrant88/search_it#37]
```
     Schnitzel  &nbsp;sind dünn geschnittene&nbsp; Fleischstücke  &nbsp;ohne&nbsp; Knochen  , die meist zusätzlich mit einem&nbsp; Fleischklopfer  &nbsp;(Plattiereisen) platt geklopft werden, was das Fleisch durch Aufbrechen der Muskelfasern zarter macht. In der Schweiz werden Schnitzel auch&nbsp; Plätzli  &nbsp;genannt.   Tannenbaum Tannenbaum  

 Im Englischen bezeichnet der Begriff&nbsp; Schnitzel  &nbsp;stets ein&nbsp; paniertes  &nbsp;Schnitzel nach Art des&nbsp; Wiener Schnitzels   . Das englische Wort für Schnitzel stammt aus der französischen Sprache und lautet&nbsp; escalope  .  



 Vor allem in Österreich wird der Begriff Schnitzel auch oft einfach mit Panier gleichgesetzt. Man kann daher auch Fischschnitzel, Zucchinischnitzel und dergleichen sagen.  
      
  
```

Plaintext sollte doch eigentlich überflüssige Leerzeichen, Leerzeilen und Entitäten wie `&nbsp;` aus dem Code schmeißen. 

Ich würde sogar soweit gehen, dass dort ausschließlich a-z,A-Z abgelegt werden und Satzzeichen wie Klammern, Anführungszeichen entfernt werden. Die sorgen doch dafür, dass man `LIKE` statt `MATCH AGAINST` verwenden muss, um Begriffe in Anführungszeichen und Klammern zu finden, oder?

Dann stand ja noch die Frage offen, was überhaupt der Vorteil ist, HTML-Code zu durchsuchen. Mögliche Antwort: Attribute wie href="", title="" und alt="" werden in der HTML-Suche indexiert.

**Comment by tyrant88** [comment]
Den genauen Sinn des plaintext plugins habe ich auch noch nicht begriffen, aber in ihm kann man mit ~\s+~ism und einem Space als Ersetzung alles auf ein Leezeichen reduzieren.

**Comment by alexplusde** [comment]
Das Plaintext-Plugin macht doch, dass alles HTML entfernt wird und dadurch Tags, sonst. HTML nicht als Keywords in der Datenbank landen. oder?

Vielleicht kann @xong noch was dazu schreiben?
