### ISSUE TITLE
Vereinheitlichung Schreibweise

### ISSUE THREAD

**Issue by alexplusde** [tyrant88/search_it#4]
Das Addon heißt `Search it` wird aber öfters als `search_it` bezeichnet. Besser nur die Klasse "search_it" nennen, aber wenn vom Addon die Rede ist, immer `Search it`. Die Datenbanktabelle wiederum heißt `searchit`, ist das beabsichtigt?

**Comment by tyrant88** [comment]
Wie es  heißen soll bin ich mir noch nicht ganz sicher. 
"Search it" im Englischen würde man es klein schreiben, aber dann ist im Fließtext nicht deutlich, dass es ein Eigenname ist.
Das wiederum wird bei Nutzung des Unterstrichs deutlich "search_it"
Auf jeden Fall hab ich (da auch ich ein Freund von Einheitlichkeit bin) die Datenbanktabelle umbenannt, also Vorsicht bei der nächsten Version.

**Comment by tyrant88** [comment]
Also das Addon heißt "Search it"
Die Klasse und Tabellen "search_it"
