### ISSUE TITLE
Manuelles Reindexieren von Artikeln und im Table Manager

### ISSUE THREAD

**Issue by alexplusde** [tyrant88/search_it#42]
Laut https://github.com/tyrant88/search_it/blob/master/plugins/reindex/README.md gab es die Möglichkeit, Artikel und YForm auch manuell zu reindexieren, allerdings gibt es die entsprechenden EPs nicht mehr.

Evtl. könnten @dergel oder @gharlan dabei helfen, diese EP wieder zur Verfügung zu stellen.

YForm:
- EP zum manuellen reindexieren, Button entsprechend an der Tabelle oder an einzelnen Datensätzen

Structure:
- EP für zusätzlichen Tab / Sidebar-Block nutzen
- Button zum manuellen Reindexieren 
- Button zum Hinzufügen in Blacklist/Whitelist (Feature gibt's ja schon innerhalb der Addons)

**Comment by tyrant88** [comment]
YForm Tabellen werden automatisch reindiziert, wenn das Häkchen bei "Reindizieren aller Spalten, wenn Tabellen mit yform oder form bearbeitet werden" gesetzt ist. Das sollten wir so dokumentieren, dass klar ist wenn man eigene Tabellen im Backend nutzt, sollte man das Häkchen setzen.

@dergel hatte mich auch daraufhingewiesen, die Reindexierung über einen cronjob laufen zu lassen. Vielleicht ist das eh eine bessere Lösung, als alle Eventualitäten einzen abfangen zu wollen...
Vielleicht auch modular: ein cronjob für Artikel, einer für DB-Spalten,...

**Comment by alexplusde** [comment]
Da man Cronjobs mittlerweile auch am Skriptende ausführen kann, würde vlt. gar nichts dagegen sprechen, eine stündilche Indizierung anzustoßen. Gut wäre es, wenn der Cronjob bereits bei der Installation erstellt werden.

**Comment by alexplusde** [comment]
Das muss ja relativ easy einzubauen sein, wenn man sich das Backup-Addon von yakamara anschaut:

https://github.com/redaxo/redaxo/blob/master/redaxo/src/addons/backup/boot.php
https://github.com/redaxo/redaxo/blob/master/redaxo/src/addons/backup/lib/cronjob.php

**Comment by tyrant88** [comment]
Das sieht vielversprechend aus. Danke für die Vorarbeit, aber das ist ein feature, das muss noch warten... ;-)

**Comment by alexplusde** [comment]
Fürs Protokoll: Ich habe den Code mal in meine Demo gehauen, noch scheint es zu krachen. Evtl. Syntaxfehler, evtl. auch was anderes.

**Comment by tyrant88** [comment]
Issue war doppelt
