### ISSUE TITLE
Doppelte Treffer vermeiden

### ISSUE THREAD

**Issue by alexplusde** [tyrant88/search_it#43]
Wenn ich das richtig verstehe, ist search_it ja eine Volltextsuche - beim Indexieren wird also nur der Inhalt durchsucht. Werden Artikelname, Kategoriename oder dergleichen nicht ausgegeben, dann werden diese Begriffe dort auch nicht indexiert. (Vielleicht nicht best practice, kommt aber vor)

Um also Meta-Infos (yrewrite_seo_description oder den Artikelnamen) zu indexieren, müssen zusätzlich noch die zugehörigen rex_article-Datenbankspalten indexiert werden. Das wiederum führt zu doppelten Treffern: 

- Ein Suchbegriff wird einmal über die Volltextsuche gefunden
- und einmal über die Datenbanksuche.

Habe ich das richtig erfasst? Lässt sich das irgendwie vermeiden? 

(Mir wäre das für die Doku wichtig, weil ich intuitiv damit rechne, dass ein Artikel nur einen Treffer darstellt, nicht zwei.)

**Comment by tyrant88** [comment]
Das Problem sehe ich noch nicht.

Das naheliegende ist: Alles was der Nutzer sehen kann, wenn er den Artikel ansieht (durch Navigation) kann er auch über die Suche finden. Davon will man keine Ausnahmen – mach keinen Sinn.

Jetzt muss ich mir überlegen, welche Spalte der Artikel-Tabelle ich jetzt noch brauche. Welche soll das sein? Wenn es noch nicht auf der Seite ist, dann ist es doch nicht doppelt?

 
 
Von: Alexander Walther [mailto:notifications@github.com] 
Gesendet: Montag, 26. September 2016 20:31
An: tyrant88/search_it
Betreff: [tyrant88/search_it] Doppelte Treffer vermeiden (#43)

 
Wenn ich das richtig verstehe, ist search_it ja eine Volltextsuche - beim Indexieren wird also nur der Inhalt durchsucht. Werden Artikelname, Kategoriename oder dergleichen nicht ausgegeben, dann werden diese Begriffe dort auch nicht indexiert. (Vielleicht nicht best practice, kommt aber vor)

Um also Meta-Infos (yrewrite_seo_description oder den Artikelnamen) zu indexieren, müssen zusätzlich noch die zugehörigen rex_article-Datenbankspalten indexiert werden. Das wiederum führt zu doppelten Treffern: 

*	Ein Suchbegriff wird einmal über die Volltextsuche gefunden
*	und einmal über die Datenbanksuche.

Habe ich das richtig erfasst? Lässt sich das irgendwie vermeiden? 

(Mir wäre das für die Doku wichtig, weil ich intuitiv damit rechne, dass ein Artikel nur einen Treffer darstellt, nicht zwei.)

**Comment by alexplusde** [comment]
Ich bau mal ein Testszenario dazu, dann wird es mindestens mir klarer. Den Effekt doppelter Treffer eines Artikels meine ich in R4 gehabt zu haben.

**Comment by alexplusde** [comment]
Gerade getestet:
Egal, ob das in R4 vorkam oder nicht - in deinem Port funktioniert alles ordnungsgemäß. Falscher Alarm.
