### ISSUE TITLE
Doku: Paginierung via FOR

### ISSUE THREAD

**Issue by alexplusde** [tyrant88/search_it#44]
Im Moment ist die Paginierung in den Beispielen (aus RexSearch) sehr einfach gelöst und gibt ggf. hunderte von Links aus, wenn es entsprechende Treffer gibt. Das könnte man im Zuge eines FOR-Addons oder einer Helferklasse besser lösen.

https://github.com/FriendsOfREDAXO/Info/issues/10

**Comment by alexplusde** [comment]
https://github.com/tyrant88/search_it/tree/doku-pagination

**Comment by alexplusde** [comment]
Features:
* Generiert eine nummerierte Liste anhand 3 Parametern (`$total, $page, $limit`)
* Syntax und Klassen definierbar
* Text für Vor/Zurück-Links definierbar
* Vor/Zurück und Erste/Letzte Seite-Link optional 
* Anzahl der Links um die aktuelle Trefferseite definierbar
* Ziel-Artikel-ID, Ziel-Hash (für Sprungmarke) definierbar

**Comment by tyrant88** [comment]
Hast dir so ne Mühe gemacht, Mist, und ich muss wieder rummäkeln... 
Ich bin halt Purist, für mich ist das eher ne Modul-Sache... 
Search it liefert mir die Ergebnisse, wie ich die dann verarbeite suche ich mir von Projekt zu Projekt aus. 
Vielleicht mit Paginierung, vielleicht mit AJAX nachladen...
Wenn du irgendeine Möglichkeit siehst..., aber wenn es dir nicht unwichtig ist, nehmen wir es...

**Comment by alexplusde** [comment]
Das ist nicht so wild. Wir können die Klasse auch auf FOR > tricks packen und darauf verweisen, weil im Grunde genommen eine Paginierung auch nicht zwingend zu einer Volltextsuche gehört und die Ausgabe ja komplett unabhängig von `search_it` ist.

**Comment by xong** [comment]
Hey, ihr seid ja schon echt weit gekommen. Find ich klasse.

Ich hatte das Suchaddon damals ausschließlich als Suchindex geplant, dass zusätzlich eine Methode anbietet, innerhalb des Index zu suchen.
Ich würde euch empfehlen, diese Trennung zwischen Index und Ausgabe beizubehalten. Die generelle Paginierung der Suchergebnisse ist ja schon durch die Methode "setLimit" möglich. Wie die Ausgabe letztendlich aussieht, würde ich aber dem Ausgabemodul überlassen.

**Comment by tyrant88** [comment]
Hi xong, 
genau das war auch mein Empfinden.

**Comment by alexplusde** [comment]
ist jetzt bei FOR > tricks und das HowTo aktualisiere ich noch, falls ich das nicht bereits gemacht habe. Passt also :)
