### ISSUE TITLE
package.yml: Support Page, Auto-Plugins

### ISSUE THREAD

**Issue by alexplusde** [tyrant88/search_it#50]
* Support-Page auf Github oder Slack ändern: https://github.com/tyrant88/search_it/blob/master/package.yml#L4 

* Vorschlag: Plugins wie Doku, Plaintext, Stats als System Plugins kennzeichnen (dann werden sie meines Wissens automatisch beim Installieren aktiviert), vgl. https://github.com/yakamara/redaxo_yform/blob/master/package.yml
https://github.com/tyrant88/search_it/blob/master/package.yml#L26

**Comment by tyrant88** [comment]
supportpage hab ich geändert. Auf github. (später soll es ja mal zu FOR)

Von den "System Plugins" halte ich nicht so viel. Doku kann man streiten, ich hab es mal dazu gemacht. Sollte ja jeder mal lesen, bzw. ohne kann man ja nicht starten.
Aber die anderen beiden sind typische plugins für mich: manche werden sie lieben, andere brauchen sie nicht.

**Comment by alexplusde** [comment]
Passt :)
