### ISSUE TITLE
File-Indexing Problem mit pdftotext 

### ISSUE THREAD

**Issue by skerbis** [tyrant88/search_it#53]
Das File-Indexing des Medienpools scheint nur mit installiertem pdftotext auf dem Server zuverlässig zu funktionieren. 

Für die Doku

**Installation in diversen Linux-Distributionen**
`yum install poppler-utils`

**Installation unter Ubuntu / Debian**
`sudo apt-get install poppler-utils`

Alternative? https://github.com/smalot/pdfparser

**Comment by tyrant88** [comment]
Bin dran, der pdfparser hat es leider auch nicht gerockt, zu mal er GPL ist.

@tbaddade mindestens dieser Hinweis von skerbis wird in die Doku wandern

**Comment by tyrant88** [comment]
siehe #57
