### ISSUE TITLE
Checkboxen sollten das checkbox-Fragment nutzen

### ISSUE THREAD

**Issue by tbaddade** [tyrant88/search_it#54]
Liste der verfügbaren Formular-Fragmente
https://github.com/redaxo/redaxo/tree/master/redaxo/src/core/fragments/core/form

**Comment by tyrant88** [comment]
muss ich mir anschauen. Ich habe ja durch Search it die Fragmente kennengelernt und auch öffentlich in der RUGRM Werbung dafür gemacht, da sollte ich sie konsequent einsetzen....

**Comment by tbaddade** [comment]
Bsp. für Checkbox findest du [hier](https://github.com/redaxo/redaxo/blob/master/redaxo/src/addons/structure/plugins/content/pages/templates.php#L300-L309).
U.a. auch eine Notiz, wenn das Label zu lang sein sollte.

**Comment by tyrant88** [comment]
Okay, Fragmente sind eingebaut. Das mit dem <input> -Tag im <label>-Tag gefällt mir aber nicht wirklich. Da muss ich dann irgendwann mein eigenes Fragment bauen ;-)

**Comment by tbaddade** [comment]
> Das mit dem -Tag im -Tag gefällt mir aber nicht wirklich

Was meinst du? Tags in Tags ist ganz normales HTML.

**Comment by tyrant88** [comment]
Einigen wir uns auf "ganz normales" HTML5. :-)
Für 4.0 oder XHTML 1.0 gilt das nicht. Da gab es z.B. die Regel das inline Elemente keine Block-Elemente enthalten dürfen...

**Comment by tbaddade** [comment]
Ich verstehe immer noch nicht an welchem HTML du dich grad störst? Was gefällt dir genau nicht?

**Comment by alexplusde** [comment]
@tyrant88 wenn du in GitHub Tags notierst, dann bitte immer mit einem Akzent markiert, so: ``<tag>``. Sonst verschwindet der Tag und sieht so aus:
![checkboxen sollten das checkbox fragment nutzen issue 54 tyrant88 search_it](https://cloud.githubusercontent.com/assets/3855487/19578235/1fa878ac-971b-11e6-87d2-a40fdc77b09e.png)

Ich vermute, du meintest, dass `<input>` in `<label>` sagt dir nicht zu. Ist aber best practice:
http://stackoverflow.com/questions/6293588/how-to-create-an-html-checkbox-with-a-clickable-label

**Comment by tyrant88** [comment]
Ach der Alex hat es wieder geblickt! Genau das meinte ich, @tbaddade sorry für die Verwirrung. 
@alexplusde Das W3C akzeptiere ich.

**Comment by alexplusde** [comment]
gern g'scheh'. :)
