### ISSUE TITLE
Panels verschieben?

### ISSUE THREAD

**Issue by tbaddade** [tyrant88/search_it#55]
Gehören diese Panels nicht eher zum Menü "Quelle"
- Suchmodus - Indexierung
- Suchergebnis - Wörter, Kategorien und Artikel von der Suche ausschließen

**Comment by tyrant88** [comment]
Ich rede mich mal teilweise raus:
"Indexierung" bestimmt WIE und WANN der Index gebildet wird, wärend "Quelle" bestimmt, WAS indexiert wird.
Und genau in diesem Sinne hast du für "Suchergebnis - Wörter, Kategorien und Artikel von der Suche ausschließen" vollkommen Recht, das muss rüber wandern.

**Comment by tbaddade** [comment]
> während "Quelle" bestimmt, WAS indexiert wird.

Und genau deshalb müsste Indexierung doch auch rüber, sagt ja schon der Paneltitle :). Es hat ja an der Stelle nichts mit dem Suchmodus zu tun.
Was wird indexiert? Offline-Artikel.

**Comment by tyrant88** [comment]
Ich hab jetzt einen neuen Reiter "Blacklist" gemacht. Und "Quelle" in "Zusätzliche Datenquellen" umbenannt. Vielleicht nicht optimal, aber schon Besser.
