### ISSUE TITLE
PDF Dateien werden teilweise nicht indexiert

### ISSUE THREAD

**Issue by tbaddade** [tyrant88/search_it#57]
Bei sehr vielen PDF-Dateien kommt die Meldung.

> is empty or could not be extracted.

In RexSearch bekomme ich zusätzlich diese Meldung beim indexieren.

> Deprecated: Non-static method pdf2txt::directConvert() should not be called statically, assuming $this from incompatible context in /addons/rexsearch/classes/class.rexsearch.inc.php on line 956

**Comment by tyrant88** [comment]
Jetzt reicht's aber mal! ;-)
Da bin ich gerade dran...
Besteht aus 
1.) einem Bug der im nächsten commit raus ist, und 
2) wenn pdftotext auf dem Server nicht installiert ist, sieht es im Moment ziemlich finster aus... XONG hat das pdf2txt selbst geschrieben, das schafft immerhin mehr als die fünf pdf2text Klassen, die ich in den letzten zwei Tagen ausprobiert habe.
Das Prinzip ist mir zwar klar, aber das liegt wohl an den aktuellen PDF Varianten. Und im Moment habe ich keine Lust es selbst zu machen.

**Comment by skerbis** [comment]
Ich denke pdftotext auf dem Server sollte einfach eine Voraussetzung sein, sonst wird nicht indiziert. 
Bei anderen CMS muss man ja auch imagemagick oder ghost oder sonstwas haben. 
Macht das Addon nicht schlechter - sondern schneller. ;-)

**Comment by tyrant88** [comment]
@skerbis Genau mit deinem Argument und dem eingefügten Hinweis in der Doku schließe ich dieses issue

**Comment by tbaddade** [comment]
pdftotext ist installiert. Die Fehler kommen dennoch. Woran kann das liegen bzw. wie müsste das PDF aussehen damit es richtig indexiert werden kann?

**Comment by tyrant88** [comment]
Sag noch mal genau was für Fehlermeldungen. Wenn das pdf z.B. nur aus einer Grafik besteht kann pdftotext wenig machen. :-)

**Comment by tbaddade** [comment]
> Sag noch mal genau was für Fehlermeldungen
searchid meldet beim indexieren `is empty or could not be extracted.` Systemlog liefert nichts.

Texte sind jedenfalls vorhanden im PDF.

**Comment by skerbis** [comment]
Ist soweit ganz logisch: a) PDF ist komprimiert, b) zu neues Format , c) Es wurden Rechte in den PDFs definiert (z.B. nicht drucken)

**Comment by tyrant88** [comment]
Nee, ich glaube der Bug is doch noch drin, bei mir indiziert er gerade auch nicht....

**Comment by skerbis** [comment]
Also bei mir indiziert er nur die PDFs nicht, in denen nur Scans drin sind. 
Habt ihr überprüft ob pdftotext  auch wirklich verwendet wird?

**Comment by skerbis** [comment]
Hab noch was gefunden: http://www.pdftotext.eu

**Comment by alexplusde** [comment]
ich kann's leider im Moment nicht testen, weil nicht produktiv im Einsatz.

**Comment by tyrant88** [comment]
So, Neuigkeiten. Ich hatte nicht darauf geachtet, dass der Indizierungsfunktion die Dateinamen unterschiedlich übergeben wurden, je nach dem ob man "Medienpool indizieren" angehakt hat oder den Ordner "media" ausgewählt hat. 
Langer Rede kurzer Sinn es sollte jetzt bei allen funktionieren. 
Wenn sich das bestätigt, würde ich gerne ein neues Release für den Installer bauen.
