### ISSUE TITLE
rex_article.name voreingestellt indexieren

### ISSUE THREAD

**Issue by alexplusde** [tyrant88/search_it#64]
Die Frage kommt immer wieder auf. Deshalb so voreinstellen, wie die meisten Nutzer das Feature erwarten.

Alternativ: In Setup-Beschreibung mit aufnehmen.

**Comment by tyrant88** [comment]
Du meinst die Leute erwarten durch die Suche etwas zu finden, was auf ihrer Website nicht steht?

**Comment by alexplusde** [comment]
Der Titel-Tag ist schon etwas, das man erwarten könnte. 

Ich baue ausschließlich Seiten, in denen der Artikelname ausgegeben wird - aber scheinbar ist das nicht immer so.

**Comment by tyrant88** [comment]
Sorry. Abgelehnt. 
Aber Verb geändert überall: ab jetzt wird nur noch "indexiert".
