### ISSUE TITLE
ErrorException beim Plugin: search_highlighter 

### ISSUE THREAD

**Issue by olien** [tyrant88/search_it#69]
`"ErrorException" thrown in /Applications/MAMP/htdocs/rex5basic5/redaxo/src/addons/search_it/plugins/search_highlighter/functions/functions_search_highlighter.php on line 30
Fatal error: Cannot redeclare search_it_search_highlighter_output() (previously declared in /Applications/MAMP/htdocs/rex5basic5/redaxo/src/addons/search_it/functions/functions_search_it.php:712)
`

**Comment by tyrant88** [comment]
Das plugin gibt es nicht mehr... bitte deinstallieren

**Comment by olien** [comment]
Ah. Ok. Danke..
