### ISSUE TITLE
Index vollständig erstellen - komplett entfernen

### ISSUE THREAD

**Issue by alexplusde** [tyrant88/search_it#7]
Eigentlich hat Schrittweise Erstellen nur Vorteile, ich empfinde den Button als obsolet.

**Comment by tyrant88** [comment]
Ich habe es noch nicht überprüft, müsste mna ma l die Performance checken, bei großen Seiten....

**Comment by tyrant88** [comment]
Sorry, bleibt. Hab ich keine Zeit und Lust zu argumentieren. ;-)

**Comment by alexplusde** [comment]
Alles gut :)
