### ISSUE TITLE
Error beim Anlegen vom Meta Info Feldern (reindex)

### ISSUE THREAD

**Issue by olien** [tyrant88/search_it#70]
"Error" thrown in /Applications/MAMP/htdocs/123/redaxo/src/addons/search_it/plugins/reindex/functions/function_reindex.php on line 14
Cannot access protected property rex_metainfo_table_expander::$tableName

**Comment by olien** [comment]
Wenn der Fehler kam lassen sich die Felder im Backend auch nicht mehr löschen...

**Comment by tyrant88** [comment]
Das Plugin „reindex“ gibt es nicht mehr, bitte in der Addon Verwaltung löschen. Das ist jetzt im addon integriert.

Die nächste Version wird die alten Plugins automatisch löschen, aber dafür wollte ich kein eigenes Release machen…

 
 
Von: Oliver Kreischer [mailto:notifications@github.com] 
Gesendet: Dienstag, 6. Dezember 2016 11:31
An: tyrant88/search_it
Betreff: [tyrant88/search_it] Error beim Anlegen vom Meta Info Feldern (reindex) (#70)

 
"Error" thrown in /Applications/MAMP/htdocs/123/redaxo/src/addons/search_it/plugins/reindex/functions/function_reindex.php on line 14
Cannot access protected property rex_metainfo_table_expander::$tableName

**Comment by olien** [comment]
ah. Hatten wir ja schonmal glaube ich. Sorry!!
