### ISSUE TITLE
Fehler bei Ähnlichkeitssuche mit konjunktiver Suche

### ISSUE THREAD

**Issue by ex-q** [tyrant88/search_it#71]
Sobald die Ähnlichkeitssuche und die konjunktive Suche beide aktiviert sind wird folgender query erzeugt:
(Keyword war "er")

WHERE ((((`plaintext` LIKE '%er%')) AND ((`plaintext` LIKE '%hoher%')) AND ((`plaintext` LIKE '%Jahr%')) AND ((`[...]

Das führt dann zu immer leeren Resultaten.

Lg

**Comment by tyrant88** [comment]
Jetzt ohne die Konsequenzen geprüft zu haben: "er" ist auch ein stopword...

**Comment by alexplusde** [comment]
Wieso steht in `plaintext` %hoher%?

**Comment by ex-q** [comment]
Ist mit allen Wörtern so (er war vllt. ein dummes beispiel). "hoher" ist denke ich ein anderes Wort aus dem Index.

**Comment by tyrant88** [comment]
Sorry, ich stehe etwas auf dem Schlauch.. also du willst sagen, trotz "AND" müssten die Ähnlichkeitsvorschläge mit "OR" verknüpft sein?

**Comment by ex-q** [comment]
Ah hab mich wohl unklar ausgedrückt.

Angenommen Ähnlichkeitssuche ist aktiviert und Suchmodus ist Konjunktiv. Der Inhalt meiner Seite ist "Ich habe ein schönes Haus" und mein Suchwort ist "schönes". Dann müsste ich ja eigentlich meine Seite finden, finde sie aber nicht da search_it versucht einen Searchquery nach dem Motto "schönes" AND "schön" AND "Schoner" AND ...

Er verknüpft also die Wörter die er als Ähnlich betrachtet mit der AND bedingung was in diesem Fall keinen Sinn macht. Hoffe das war etwas klarer :)

**Comment by tyrant88** [comment]
Ja, dann hab ich dich doch einigermaßen richtig verstanden (wer hat auch den doofen Schlauch da hin gelegt :-) - ich schaue danach. Danke.

**Comment by ex-q** [comment]
Cool, Danke! :-)

**Comment by tyrant88** [comment]
Fixed. Morgen gibt es ein neues Release.
