### ISSUE TITLE
"Error" thrown in settings.mode.php on line 52 [] operator not supported for strings

### ISSUE THREAD

**Issue by phoebusryan** [tyrant88/search_it#72]
Seit PHP 7.1.. Schuld ist diese Zeile:
https://github.com/tyrant88/search_it/blob/master/pages/settings.mode.php#L48

Sollte $content = [] sein.

**Comment by tyrant88** [comment]
Danke! fixed.

**Comment by phoebusryan** [comment]
Sicher, auf Github ist es noch '' statt [] ;)
