### ISSUE TITLE
search_it  Artikel (ADD, EDIT, DELETE) vs. if(rex::isBackend())

### ISSUE THREAD

**Issue by skerbis** [tyrant88/search_it#75]
Ist diese Aktion aktiviert,  kann es dazu kommen, dass if(rex::isBackend()) nicht beachtet wird. 

```
<?php 
if(rex::isBackend())
{
echo 'Die Ausgabe erfolgt im Frontend';
}
else {
$groups = rex_ycom_auth::getUser()->getValue('ycom_groups');
$grouplist = explode(',',$groups);

.... usw. 
```
In diesem Fall wird rex_ycom_auth::getUser() aufgerufen, obwohl der Redakteur im Backend ist. 

Konfiguration bei dem der Fehler auftritt
![bildschirmfoto 2017-01-18 um 13 08 09](https://cloud.githubusercontent.com/assets/791247/22063488/5e0e8a5a-dd7f-11e6-8dd3-0d153bd39f3e.png)

**Comment by tyrant88** [comment]
Hi, Thomas,
kannst du mir das noch mal beschreiben, wie ich den Fehler reproduzieren kann?

Wo steht der Code den du schriebst? Im Template oder in einem Addon von dir? 
Und passiert es dann, wenn du einen Artikel neu anlegst (ADD), änderst (EDIT) oder löschst (DELETE)?

**Comment by tyrant88** [comment]
Gibt es eigentlich eine Fehlermeldung, im Syslog, wenn der Extensionpoint greift?

**Comment by skerbis** [comment]
hi ... den kompletten Code gebe ich Dir gerne per Slack. Es handelt sich hierbei um ein Modul, also eine Artikelausgabe. Im Syslog konnte ich keinen Fehler finden.

**Comment by tyrant88** [comment]
Ist kein Bug.
Das Modul wirft auch im Frontend einen Fehler, deshalb sollte es auch nicht stören, wenn es im Backend beim Artikel-Update einen Fehler wirft, wenn man search it bittet, bei Änderungen zu reindexieren.
