### ISSUE TITLE
Dateisuche: Verzeichnisstruktur wird nicht tiefer.

### ISSUE THREAD

**Issue by alexplusde** [tyrant88/search_it#9]
Normalerweise müsste ich "media" auswählen, woraufhin mir alle Unterordner von "media" angezeigt würden. Stattdessen erscheint wieder Ebene 0.

![image](https://cloud.githubusercontent.com/assets/3855487/18203269/3f0cf6d0-7116-11e6-99c7-99336bda0006.png)

**Comment by tyrant88** [comment]
works.
